version: '3'

services:
  velodium:
    image: "glx"
    environment:
      - "DISPLAY=$DISPLAY"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - ~/.Xauthority:/root/.Xauthority
    devices:
      - "/dev/dri:/dev/dri"
    ports:
      - 2370:2370
    network_mode: "host"
  #aimodule:
  #  build:
